name: publish to nuget
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: dotnet build
        run: dotnet build -c Release -o . src/openapi-shl/openapi-shl.csproj

      - name: dotnet nuget push
        run: |
          dotnet nuget SetApiKey ${{ secrets.NUGET_API_KEY }}
          dotnet nuget push *.snupkg
          dotnet nuget push *.nupkg
          