name: publish to nuget
on:
  push:
    branches:
      - main

env:
  NETCORE_VERSION: '6.0.104'

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: dotnet build
        run: dotnet build -c Release -o . src/openapi-shl/openapi-shl.csproj

      - name: dotnet nuget push
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }}
          